[package]
name = "bristol-circuit"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.208", features = ["derive"] }
serde_json = "1.0.125"
strum = "0.26.3"
strum_macros = "0.26.4"
thiserror = "1.0.63"
